### PR TITLE
Fix some stuff.

### LINKED ISSUE #138: this should be reverted now that the problem is fixed
https://github.com/cloudpeers/tlfs/blob/c7dd9d260ee6e5a624102cc55c3b1dfed4828f13/src/sync.rs#L110

### PR DESCRIPTION
**Pull request by dvc94ch**
Closes #138

### CODE REVIEW

File: api/dart/lib/sdk.dart [hunk 1]
```diff
@@ -11,8 +11,7 @@ Future<tlfs.Sdk> _loadSdk(String appname) async {
   final documentsDirectory = await getApplicationDocumentsDirectory();
   final dbPath = join(documentsDirectory.path, appname, 'db');
   await Directory(dbPath).create(recursive: true);
-  final assetName =
-      'assets/{appname}.tlfs.rkyv'.replaceAll('{appname}', appname);
+  final assetName = 'assets/$appname.tlfs.rkyv';
```
Comment (rklaehn) [inline api/dart/lib/sdk.dart:14]: So this is dart string interpolation?

File: api/src/lib.rs [hunk 2]
```diff
@@ -9,16 +9,16 @@ use tlfs_crdt::ArchivedSchema;
 
 pub struct Sdk(tlfs::Sdk);
 
-pub async fn create_persistent(path: &str, package: &[u8]) -> Result<Sdk> {
+pub async fn create_persistent(path: String, package: Vec<u8>) -> Result<Sdk> {
```
Comment (rklaehn) [inline api/src/lib.rs:12]: So this is to be on the safe side regarding lifetimes?

**Review by rklaehn — APPROVED** [review]

File: api/src/lib.rs (hunk 2 above)
Comment (dvc94ch) [reply api/src/lib.rs:12]: This should fix your issue for now. It's likely we'll remove support for borrowed data, because there isn't much to gain anyway. We currently do a full copy in any case.

File: api/dart/lib/sdk.dart (hunk 1 above)
Comment (dvc94ch) [reply api/dart/lib/sdk.dart:14]: Yes
