### PR TITLE
ORArray: Correctly handle nested structs

### LINKED ISSUE #126: array is broken

### PR DESCRIPTION
**Pull request by wngr**
closes #126

### CODE REVIEW

File: api/js/index.ts [hunk 1]
```diff
@@ -192,8 +193,14 @@ const mkProxy = <T extends object>(doc: Doc, cursor_?: Cursor): T => {
         case "valueOf":
           return undefined
         case "toString": {
-          throw new Error(`Method ${p} not implemented in TLFS proxy. Please file a bug and/or use the document API directly to work around.`)
+
+          return function () { return 'FIXME' }
```
Comment (wngr) [inline api/js/index.ts:197]: will fix in subsequent PR.

**Review by dvc94ch — APPROVED** [review]

**Comment by dvc94ch** [comment]
Is this one ready to merge?
